export type Interest =
  | 'alcohol'
  | 'beer'
  | 'reading'
  | 'learning'
  | 'adrenaline'
  | 'coding'
  | 'coffee'
  | 'working'
  | 'tech'
  | 'knitting'
  | 'photography'
  | 'art'
  | 'style'
  | 'golf'
  | 'sport'
  | 'hiking'
  | 'emotional'
  | 'friendship'
  | 'relationship'
  | 'cooking'
  | 'vegan'
  | 'laughter'
  | 'food'
  | 'junk_food'
  | 'pizza'
  | 'nature'
  | 'plants'
  | 'gardening'
  | 'instruments'
  | 'guitar'
  | 'music'
  | 'video_games'
  | 'painting'
  | 'pottery'
  | 'music_production'
  | 'electronic_music'
  | 'shuttlecock'
  | 'racket_sports'
  | 'skateboarding'
  | 'extreme_sport'
  | 'snorkling'
  | 'water_sports'
  | 'intellectualism'
  | 'star_wars'
  | 'nerd_culture'
  | 'tidiness'
  | 'apple_tech'
  | 'interior_design'
  | 'comfiness'
  | 'retro_culture'
  | 'creative_activities'
  | 'karaoke'
  | 'comedy'
  | 'theatre'
  | 'performing'
  | 'singing'
  | 'dancing'
  | 'live_music'
  | 'night_life'
  | 'film'
  | 'television'
  | 'swimming'
  | 'meditation'
  | 'mental_health'
  | 'spirituality'
  | 'fishing'
  | 'travelling'
  | 'exploration'
  | 'board_games'
  | 'card_games'
  | 'minigolf'
  | 'bowling'
  | 'yoga'
  | 'gambling'
  | 'cycling';

export type ActivityType =
  | 'active'
  | 'social'
  | 'amusement'
  | 'self_improvement'
  | 'outgoing';

export type DayPeriod =
  | 'morning'
  | 'afternoon'
  | 'early_evening'
  | 'late_evening';

export const chronologicallyOrderedDayPeriods = [
  'morning',
  'afternoon',
  'early_evening',
  'late_evening',
];
